### PR TITLE
Add Capacitor 6 support

### PR DESCRIPTION
**Pull request by jeremymouton**
This pull request adds support for Capacitor 6 and exports `FileChunkServerInfo` for type checking.

### CODE REVIEW

**Comment by jeremymouton** [comment]
Successfully tested on Android and iOS. Please let me know if you find any issues.

**Comment by qrclip** [comment]
Hello,
I just need a little more time to check the changes to the package files to be sure nothing is wrong ... sorry, but I need to be sure, even though you look real :)

**Comment by jeremymouton** [comment]
No problem, just wanted to share our work if it can save anyone some time!

**Comment by qrclip** [comment]
Thanks it's updated

**Pull request merged**
